cabal: Add missing gio-unix dependency
On Nix, the build fails with

```
c-sources/pcap-monitor.c:28:10: error:
     fatal error: gio/gunixinputstream.h: No such file or directory
     #include <gio/gunixinputstream.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~
```

This commit fixes that.